//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_ProfessorOuter
    {
        public int Id { get; set; }
        public string uid { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string position { get; set; }
        public string department { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string area { get; set; }
        public string profession { get; set; }
        public string office { get; set; }
        public string stuNumPG { get; set; }
        public string referee { get; set; }
        public string location { get; set; }
        public string Account { get; set; }
    }
}
