//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.ComponentModel.DataAnnotations;

namespace Apps.Models.Sys
{
	public class Virtual_MIS_ProfessorOuterModel
	{
		public virtual int Id { get; set; }
		public virtual string uid { get; set; }
		public virtual string name { get; set; }
		public virtual string sex { get; set; }
		public virtual string position { get; set; }
		public virtual string department { get; set; }
		public virtual string mobile { get; set; }
		public virtual string email { get; set; }
		public virtual string area { get; set; }
		public virtual string profession { get; set; }
		public virtual string office { get; set; }
		public virtual string stuNumPG { get; set; }
		public virtual string referee { get; set; }
		public virtual string location { get; set; }
		public virtual string Account { get; set; }
			
	}

}
