//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.MIS.IDAL;

namespace Apps.MIS.DAL
{
	public partial class MIS_Article_CategoryRepository : CommonRepository<MIS_Article_Category>
	{
		public MIS_Article_CategoryRepository(DBContainer db) : base(db)
		{
			
		}
	}
}
