//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Apps.Models;
using Apps.Models.Sys;
using Apps.MIS.IBLL;
using Apps.MIS.IDAL;
using Microsoft.Practices.Unity;
using Apps.Common;
using Apps.BLL.Core;

namespace Apps.MIS.BLL
{
	public class Virtual_MIS_PersonBLL 
	{
		[Dependency]
        public IMIS_PersonRepository m_Rep { get; set; }

		public DBContainer db = new DBContainer();
        /// <summary>
        /// 获取列表
        /// </summary>
        /// <param name="pager">JQgrid分页</param>
        /// <param name="queryStr">搜索条件</param>
        /// <returns>列表</returns>
        public virtual List<MIS_PersonModel> GetList(ref GridPager pager,string queryStr)
        {

            IQueryable<MIS_Person> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
										a => (a.Id!=null&&a.Id.Contains(queryStr))
															||  (a.Name!=null&&a.Name.Contains(queryStr))
														||  (a.Sex!=null&&a.Sex.Contains(queryStr))
														
														||  (a.IDCard!=null&&a.IDCard.Contains(queryStr))
														||  (a.Phone!=null&&a.Phone.Contains(queryStr))
														||  (a.Email!=null&&a.Email.Contains(queryStr))
														||  (a.Address!=null&&a.Address.Contains(queryStr))
														
														||  (a.Region!=null&&a.Region.Contains(queryStr))
														||  (a.Category!=null&&a.Category.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            List<MIS_PersonModel> modelList = (from r in queryData
                                              select new MIS_PersonModel
                                              {
                                                 													 Id = r.Id,
                                                  													 Name = r.Name,
                                                  													 Sex = r.Sex,
                                                  													 Age = r.Age,
                                                  													 IDCard = r.IDCard,
                                                  													 Phone = r.Phone,
                                                  													 Email = r.Email,
                                                  													 Address = r.Address,
                                                  													 CreateTime = r.CreateTime,
                                                  													 Region = r.Region,
                                                  													 Category = r.Category,
                                                  
                                              }).ToList();
            return modelList;
        }
        /// <summary>
        /// 创建一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="model">模型</param>
        /// <returns>是否成功</returns>
        public virtual bool Create(ref ValidationErrors errors, MIS_PersonModel model)
        {
            try
            {
                MIS_Person entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.add(Suggestion.PrimaryRepeat);
                    return false;
                }
                entity = new MIS_Person();
                					entity.Id = model.Id;
                    					entity.Name = model.Name;
                    					entity.Sex = model.Sex;
                    					entity.Age = model.Age;
                    					entity.IDCard = model.IDCard;
                    					entity.Phone = model.Phone;
                    					entity.Email = model.Email;
                    					entity.Address = model.Address;
                    					entity.CreateTime = model.CreateTime;
                    					entity.Region = model.Region;
                    					entity.Category = model.Category;
                    
                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.add("插入失败");
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                //ExceptionHander.WriteException(ex);
                return false;
            }
        }
        /// <summary>
        /// 删除一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="id">id</param>
        /// <returns>是否成功</returns>
        public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    errors.add(Suggestion.DeleteFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

        /// <summary>
        /// 修改一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="model">模型</param>
        /// <returns>是否成功</returns>
        public virtual bool Edit(ref ValidationErrors errors, MIS_PersonModel model)
        {
            try
            {
                MIS_Person entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.add(Suggestion.Disable);
                    return false;
                }
                					entity.Id = model.Id;
                    					entity.Name = model.Name;
                    					entity.Sex = model.Sex;
                    					entity.Age = model.Age;
                    					entity.IDCard = model.IDCard;
                    					entity.Phone = model.Phone;
                    					entity.Email = model.Email;
                    					entity.Address = model.Address;
                    					entity.CreateTime = model.CreateTime;
                    					entity.Region = model.Region;
                    					entity.Category = model.Category;
                    


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.add(Suggestion.EditFail);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                //ExceptionHander.WriteException(ex);
                return false;
            }
        }
        /// <summary>
        /// 判断是否存在实体
        /// </summary>
        /// <param name="id">主键ID</param>
        /// <returns>是否存在</returns>
        public virtual bool IsExist(string id)
        {
            return m_Rep.IsExist(id);
        }
        /// <summary>
        /// 根据ID获得一个实体
        /// </summary>
        /// <param name="id">id</param>
        /// <returns>实体</returns>
        public virtual MIS_PersonModel GetById(string id)
        {
            if (IsExist(id))
            {
                MIS_Person entity = m_Rep.GetById(id);
                MIS_PersonModel model = new MIS_PersonModel();
                					 model.Id = entity.Id;
                    					 model.Name = entity.Name;
                    					 model.Sex = entity.Sex;
                    					 model.Age = entity.Age;
                    					 model.IDCard = entity.IDCard;
                    					 model.Phone = entity.Phone;
                    					 model.Email = entity.Email;
                    					 model.Address = entity.Address;
                    					 model.CreateTime = entity.CreateTime;
                    					 model.Region = entity.Region;
                    					 model.Category = entity.Category;
                    
                return model;
            }
            else
            {
                return null;
            }
        }
	}
}
