//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Apps.Models;
using Apps.Models.Sys;
using Apps.IBLL;
using Apps.IDAL;
using Microsoft.Practices.Unity;
using Apps.Common;
using Apps.BLL.Core;

namespace Apps.BLL
{
	public class Virtual_SysModuleBLL 
	{
		[Dependency]
        public ISysModuleRepository m_Rep { get; set; }

		public DBContainer db = new DBContainer();
        /// <summary>
        /// 获取列表
        /// </summary>
        /// <param name="pager">JQgrid分页</param>
        /// <param name="queryStr">搜索条件</param>
        /// <returns>列表</returns>
        public virtual List<SysModuleModel> GetList(ref GridPager pager,string queryStr)
        {

            IQueryable<SysModule> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
										a => (a.Id != null && a.Id.Contains(queryStr))
															|| (a.Name != null && a.Name.Contains(queryStr))
														|| (a.EnglishName != null && a.EnglishName.Contains(queryStr))
														|| (a.ParentId != null && a.ParentId.Contains(queryStr))
														|| (a.Url != null && a.Url.Contains(queryStr))
														|| (a.Iconic != null && a.Iconic.Contains(queryStr))
														
														|| (a.Remark != null && a.Remark.Contains(queryStr))
														
														|| (a.CreatePerson != null && a.CreatePerson.Contains(queryStr))
														
														
														
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            List<SysModuleModel> modelList = (from r in queryData
                                              select new SysModuleModel
                                              {
                                                 													 Id = r.Id,
                                                  													 Name = r.Name,
                                                  													 EnglishName = r.EnglishName,
                                                  													 ParentId = r.ParentId,
                                                  													 Url = r.Url,
                                                  													 Iconic = r.Iconic,
                                                  													 Sort = r.Sort,
                                                  													 Remark = r.Remark,
                                                  													 Enable = r.Enable,
                                                  													 CreatePerson = r.CreatePerson,
                                                  													 CreateTime = r.CreateTime,
                                                  													 IsLast = r.IsLast,
                                                  													 Version = r.Version,
                                                  
                                              }).ToList();
            return modelList;
        }
        /// <summary>
        /// 创建一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="model">模型</param>
        /// <returns>是否成功</returns>
        public virtual bool Create(ref ValidationErrors errors, SysModuleModel model)
        {
            try
            {
                SysModule entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.add(Suggestion.PrimaryRepeat);
                    return false;
                }
                entity = new SysModule();
                					entity.Id = model.Id;
                    					entity.Name = model.Name;
                    					entity.EnglishName = model.EnglishName;
                    					entity.ParentId = model.ParentId;
                    					entity.Url = model.Url;
                    					entity.Iconic = model.Iconic;
                    					entity.Sort = model.Sort;
                    					entity.Remark = model.Remark;
                    					entity.Enable = model.Enable;
                    					entity.CreatePerson = model.CreatePerson;
                    					entity.CreateTime = model.CreateTime;
                    					entity.IsLast = model.IsLast;
                    					entity.Version = model.Version;
                    
                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.add("插入失败");
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                //ExceptionHander.WriteException(ex);
                return false;
            }
        }
        /// <summary>
        /// 删除一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="id">id</param>
        /// <returns>是否成功</returns>
        public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    errors.add(Suggestion.DeleteFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

        /// <summary>
        /// 修改一个实体
        /// </summary>
        /// <param name="errors">持久的错误信息</param>
        /// <param name="model">模型</param>
        /// <returns>是否成功</returns>
        public virtual bool Edit(ref ValidationErrors errors, SysModuleModel model)
        {
            try
            {
                SysModule entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.add(Suggestion.Disable);
                    return false;
                }
                					entity.Id = model.Id;
                    					entity.Name = model.Name;
                    					entity.EnglishName = model.EnglishName;
                    					entity.ParentId = model.ParentId;
                    					entity.Url = model.Url;
                    					entity.Iconic = model.Iconic;
                    					entity.Sort = model.Sort;
                    					entity.Remark = model.Remark;
                    					entity.Enable = model.Enable;
                    					entity.CreatePerson = model.CreatePerson;
                    					entity.CreateTime = model.CreateTime;
                    					entity.IsLast = model.IsLast;
                    					entity.Version = model.Version;
                    


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.add(Suggestion.EditFail);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.add(ex.Message);
                ExceptionHandler.WriteException(ex);
                //ExceptionHander.WriteException(ex);
                return false;
            }
        }
        /// <summary>
        /// 判断是否存在实体
        /// </summary>
        /// <param name="id">主键ID</param>
        /// <returns>是否存在</returns>
        public virtual bool IsExist(string id)
        {
            return m_Rep.IsExist(id);
        }
        /// <summary>
        /// 根据ID获得一个实体
        /// </summary>
        /// <param name="id">id</param>
        /// <returns>实体</returns>
        public virtual SysModuleModel GetById(string id)
        {
            if (IsExist(id))
            {
                SysModule entity = m_Rep.GetById(id);
                SysModuleModel model = new SysModuleModel();
                					 model.Id = entity.Id;
                    					 model.Name = entity.Name;
                    					 model.EnglishName = entity.EnglishName;
                    					 model.ParentId = entity.ParentId;
                    					 model.Url = entity.Url;
                    					 model.Iconic = entity.Iconic;
                    					 model.Sort = entity.Sort;
                    					 model.Remark = entity.Remark;
                    					 model.Enable = entity.Enable;
                    					 model.CreatePerson = entity.CreatePerson;
                    					 model.CreateTime = entity.CreateTime;
                    					 model.IsLast = entity.IsLast;
                    					 model.Version = entity.Version;
                    
                return model;
            }
            else
            {
                return null;
            }
        }
	}
}
